# Generated by Django 3.2.2 on 2021-05-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
