# Generated by Django 3.2.2 on 2021-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Breakfast', max_length=9),
        ),
    ]
