# Generated by Django 3.2.2 on 2021-05-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_menu_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
