# Generated by Django 3.2.2 on 2021-05-10 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_laundry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
